development:
  host: localhost
  database: eblb_development

test:
  host: localhost
  database: eblb_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
